name: 'Docker Build'
description: 'Build a Docker image with customizable Dockerfile, image name, and tag'

inputs:
  path_dockerfile:
    description: 'src/main/docker/Dockerfile.jvm'
    default: 'Dockerfile'
  image_name:
    description: 'academy'
  tag_name:
    description: '1754052266'

runs:
  using: composite
  steps:
    - name: Define Tag name
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
        echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
        echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Define Image name
      run: echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}:${{ env.TAG }}" >> $GITHUB_ENV
      shell: bash

    - name: Docker Build
      run: docker build .  --file ${{ inputs.path_dockerfile }} --tag ${{ env.DOCKER_IMAGE_NAME }}
      shell: bash

    - name: Verify Docker Images
      run: docker images
      shell: bash