name: Java CI with Maven

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/maven_build
      - uses: ./.github/actions/docker_build
        with:
          path_dockerfile: src/main/docker/Dockerfile.jvm
          image_name: ${{ vars.DOCKERHUB_USERNAME }}/workstation-rack-module
          tag_name: v1
      - uses: ./.github/actions/docker_push
        with:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}