name: Java CI with Maven

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/docker_push
              with:
                DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
                DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                    java-version: '21'
                    distribution: 'temurin'
                    cache: maven
        
            - name: Run Maven build custom action
              uses: ./.github/actions/maven_build

            - name: Build Docker image with explicit tag
              uses: ./.github/actions/docker_build
              with:
                image_name: academy
                tag_name: v1.0.0
                path_dockerfile: src/main/docker/Dockerfile.jvm

            - name: Build Docker image with timestamp tag
              uses: ./.github/actions/docker_build
              with:
                image_name: academy
                path_dockerfile: src/main/docker/Dockerfile.jvm


    list_images:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: List Docker images
          run: docker image ls